services:
  date:
    build:
      context: ./date-service
      dockerfile: Dockerfile
    container_name: date-service

  result:
    build:
      context: ./result-service
      dockerfile: Dockerfile
    container_name: result-service
    env_file:
      - .env
    depends_on:
      - date

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./result-service/static:/static
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./certbot/www:/var/www/certbot
      - ./certbot/data:/etc/letsencrypt
    depends_on:
      - result

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certbot/www:/var/www/certbot
      - ./certbot/data:/etc/letsencrypt
    # этот сервис используем только вручную для первого получения сертификата:
    # docker compose run --rm certbot certonly ...  файл certbot

  certbot-renew:
    image: certbot/certbot
    container_name: certbot-renew
    volumes:
      - ./certbot/www:/var/www/certbot
      - ./certbot/data:/etc/letsencrypt
      - /var/run/docker.sock:/var/run/docker.sock
    entrypoint: >
      sh -c 'while :; do
        certbot renew --webroot -w /var/www/certbot &&
        docker exec nginx nginx -s reload;
        sleep 12h;
      done'
    depends_on:
      - nginx
